DROP DATABASE IF EXISTS `%s`;
CREATE DATABASE IF NOT EXISTS `%s` CHARACTER SET utf8 COLLATE utf8_general_ci;
use `%s`;

CREATE TABLE `article` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO article (`created_at`, `title`, `text`) VALUES (1470648451, 'article1', 'Tube-eye albacore morid cod kaluga: swordtail combfish zebra pleco." European flounder barracudina sand eel grunt common tunny. Whiptail gulper bango, plownose chimaera spinefoot neon tetra: pickerel, thresher shark smalleye squaretail, scorpionfish southern flounder. Barracuda channel catfish ghoul Black angelfish titan triggerfish Black angelfish Russian sturgeon cichlid channel bass. Poacher: clown loach Rio Grande perch. Atlantic salmon Australasian salmon swordtail aruana fusilier fish turbot seahorse rockweed gunnel. Bocaccio round stingray scissor-tail rasbora, scabbard fish mosquitofish elephantnose fish ghost pipefish Indian mul barracudina, "batfish," dab bonefish deepwater cardinalfish.');
INSERT INTO article (`created_at`, `title`, `text`) VALUES (1470648857, 'article2', 'Barreleye cornetfish, yellowtail amberjack hairtail, spiny dogfish, topminnow kelp perch. Indian mul sea bass, "sand tilefish scaleless black dragonfish?" Vendace, warbonnet sand eel roanoke bass Hammerjaw rock cod snubnose parasitic eel morid cod springfish basking shark. Walleye medusafish buri livebearer round whitefish tailor Rainbow trout, mustache triggerfish, sablefish leaffish pencil catfish, torrent fish. Kingfish yellowfin croaker sauger garibaldi hatchetfish, buffalofish; bass boarfish, "tadpole fish," zebra oto bango. Peacock flounder righteye flounder lampfish electric catfish loweye catfish, whitebait Black triggerfish North American darter threadsail pencil catfish! Rivuline glowlight danio fierasfer northern pike yellowtail snapper speckled trout driftfish koi. Jellynose fish catalufa striped burrfish halfmoon thornfish climbing perch silver dollar. Anemonefish Long-finned sand diver, threadtail thornfish. Denticle herring, walleye pollock longfin smelt trahira gulper eel sauger halfmoon garden eel, spiny dwarf catfish. Tubeshoulder; crocodile icefish kaluga, pike characid northern sea robin Sacramento splittail California flyingfish mustard eel. Mudskipper hillstream loach wolf-herring walu northern pike South American Lungfish frogmouth catfish knifejaw yellowtail clownfish; Black mackerel.');
INSERT INTO article (`created_at`, `title`, `text`) VALUES (1470642451, 'article3', 'Atlantic eel murray cod grenadier; starry flounder algae eater red snapper tapetail mud minnow duckbill eel. Gar eucla cod barfish mola mola sunfish salmon herring smelt priapumfish yellowfin pike basking shark torrent fish. Crevice kelpfish, yellowbelly tail catfish: mackerel electric eel mackerel shark prickly shark barramundi? Bengal danio southern smelt sixgill shark plownose chimaera salmon shark South American Lungfish. California halibut betta Rattail catalufa sargassum fish Mozambique tilapia. River stingray yellowtail amberjack steelhead whitefish Atlantic silverside round stingray. Reef triggerfish kuhli loach ghost fish pumpkinseed marlin deepwater stingray stickleback lungfish salamanderfish. Bluefish wrasse golden dojo chub Atlantic eel Celebes rainbowfish weatherfish ray tang Sevan trout snailfish weever! Icefish whalefish rice eel tube-snout ponyfish ray, sheepshead Pacific trout ronquil. Livebearer Long-finned sand diver, boga slender mola. Temperate bass, "piranha amago sandburrower Black pickerel," sandperch spikefish banjo catfish bass yellowbelly tail catfish blackchin, dartfish vimba, "scissor-tail rasbora." Black prickleback rock cod mustache triggerfish Atlantic cod Bitterling loweye catfish sabertooth fish aholehole Blind shark, gouramie.');
INSERT INTO article (`created_at`, `title`, `text`) VALUES (1470643451, 'article4', 'Northern pearleye cow shark bottlenose Port Jackson shark torpedo firefish, smalleye squaretail Mozambique tilapia longnose dace. Longfin smelt oceanic whitetip shark monkfish ghost knifefish pearlfish, spinyfin drum giant gourami mora grunt armorhead catfish dragon goby? Blenny northern anchovy; Mozambique tilapia koi whalefish panga, marlin. Char round whitefish sand lance sailbearer tompot blenny; stonecat Gila trout snipe eel. Bull shark boxfish fusilier fish--pilot fish peladillo temperate ocean-bass boafish, trumpetfish, loach goby: wasp fish Cherubfish; smalltooth sawfish ling nase. Spadefish sábalo pricklefish gray reef shark danio barracudina flying characin! Snake mudhead. Ocean perch longnose chimaera medaka emperor clownfish herring smelt bocaccio Moorish idol common carp duckbilled barracudina. Pupfish Moorish idol surfperch deep sea bonefish hammerhead shark; yellowfin cutthroat trout burrowing goby. Stonecat, tripod fish footballfish, prowfish grouper stickleback lightfish batfish long-whiskered catfish. Sole fangtooth: naked-back knifefish bluntnose knifefish Black angelfish black bass.');
INSERT INTO article (`created_at`, `title`, `text`) VALUES (1470645451, 'article5', 'Lanternfish darter yellowfin pike Ganges shark lined sole triplefin blenny sleeper shark gray mullet European perch mora sculpin pikehead gizzard shad redside South American Lungfish. Sergeant major dwarf loach; grayling, "loach minnow, hussar threespine stickleback yellowtail snapper smooth dogfish stoneroller minnow." Tui chub glass catfish Redfin perch dogfish shark shortnose chimaera pupfish, "ghost pipefish." Creek chub surf sardine flathead catfish mud minnow. Forehead brooder cuckoo wrasse footballfish requiem shark marblefish speckled trout ilisha Blacksmelt cat shark barramundi torrent fish triplespine frogfish, eel guitarfish sand eel California smoothtongue, gray eel-catfish. Mooneye zebrafish eucla cod stream catfish Rainbow trout. Moses sole pirarucu European perch stonecat southern sandfish burbot California smoothtongue glass catfish lemon sole grayling. Rainbow trout bluntnose knifefish stream catfish long-finned char? Morwong wasp fish; pomfret Pacific saury stonecat, muskellunge; tiger shark blue danio; tope, pipefish dragonfish dusky grouper Bombay duck dogfish mustache triggerfish x-ray tetra.');